Fix normalizing of probabilistic grammars
Herb-AI/HerbGrammar.jl pull request #82
Opened 2024-07-17 08:26 UTC by nicolaefilat

This is required for Probe tests to work.

Before the probabilities were normalized per type, now they are normalized across all rules. 
If this change is good, I would also have to change the `normalize!` normalizes probabilities per type (this is only called when adding a new probabilistic rule to the grammar)

2024-07-17 09:17 UTC, ReubenJ commented
Thanks! Let's keep the default behavior as-is (`normalize!` normalizes the probabilities per type)—this is the classic definition of a PC[F|S]G. For Probe, we need this strategy of normalizing over all rules, disregarding type. Some options.

Add something like `bytype` with a default of `true`:
```julia
function normalize!(g, bytype=true)
    ...
end
```

Maybe more explicit with an `Enum`:

```julia
@enum NormalizationStrategy bytype all

function normalize!(g, strategy=NormalizationStrategy.bytype)
```

Can we think of other ways to normalize? Both solutions are a bit rigid because users of `Herb` couldn't cleanly introduce their own normalization strategy without modifying/contributing to the package to either add/change the keyword or add an option to the enum. A clean solution might introduce a trait for normalization strategy and a different type for Probe grammars—this smells of overengineering for the time being. @sebdumancic @THinnerichs @pwochner thoughts?

2024-07-17 11:07 UTC, THinnerichs commented
1. Don't think another normalization strategy is necessary, and we should leave it indeed with bytype. 
This is what we usually need during enumeration/exploration/iterating programs.
Just make sure you then also normalize with respect to the current domain, as some rules might be pruned by our constraint system. 

2. Do you actually need it over all rules?

![image](https://github.com/user-attachments/assets/360767e0-ca56-4b4f-9efb-6d8d1fc9f41c)

This is the probability update from the Probe paper

2024-07-17 11:57 UTC, nicolaefilat commented
@THinnerichs you are right, for the grammar update we do not need that but to initialize the probe search procedure we have to start from every rule having the same probability.
![image](https://github.com/user-attachments/assets/2abb2e94-e0e7-4e05-8a7f-0adf4f78d90b)

2024-07-17 11:57 UTC, ReubenJ commented
Also, if this probe-specific way of updating grammars is indeed probe-specific, then maybe we should not introduce this change at all and make the probability update procedure for Probe into a different function. Would this make things difficult for your implementation, @nicolaefilat?

2024-07-17 13:06 UTC, sebdumancic commented
yes, indeed, probabilistic grammars should normalise per type of rule. Otherwise, they lose their meaning. It might be that Probe actually does that es well, it is just a bit convoluted explained. (and again, we can change Probe for the better ;) )

To get rules of the same probability, in probabilistic grammar, that would actually mean the following:
 - every type has the same probability of being selected ; let's term that as $p_{type}$
 - every rule of the particular type, let's say there are $N$ of them, has the probability $\frac{p_{type}}{N}$

2024-07-17 13:29 UTC, nicolaefilat commented
I ran the probe tests again without normalizing on all the rules and it seems to work. @sebdumancic you were right!

2024-07-18 07:01 UTC, ReubenJ requested changes

2024-07-18 07:01 UTC, ReubenJ commented on src/csg/probabilistic_csg.jl
If the alternative strategy is not needed, let's remove the changes to `normalize!`, but keep the fix for double normalization in `expr2pcsgrammar`.

2024-07-18 07:01 UTC, ReubenJ commented on test/test_csg.jl
and this test can be dropped

2024-07-18 12:23 UTC, ReubenJ approved these changes

2024-07-18 12:27 UTC, merged